# Generated by Django 4.2.9 on 2024-02-08 13:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Yogurt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('Address1', models.CharField(blank=True, max_length=200)),
                ('Address2', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(blank=True, max_length=200)),
                ('State', models.CharField(blank=True, max_length=200)),
                ('Zipcode', models.CharField(blank=True, max_length=200)),
                ('Country', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
